### ISSUE TITLE
[Feature Request] Find player GUID using player name

### ISSUE THREAD

**Issue by FliesWithWind** [Yoshi-E/ArmaRconDiscordBot#30]
Hey,

Really love the work you've done. :)

Any chance you could add "!find <Nickname>" command for getting player guid using player nickname?

**Comment by Yoshi-E** [comment]
There are already 2 commands for that in the rcon_database module:
!find <field> <value>
!find_linked <BEID>

The command find allows you to search the database, example below.
the values need to match exactly, e.g. yoshi_e would not be valid when the nick name is "Yoshi_E"
Closest match stuff is planned, but has a low priority for now.

- !find name Yoshi_E --> {'ID': '2', 'name': 'Yoshi_E', 'beid': '3cd2b01a123aaada2312aaa124cbawdaw', 'ip': '21.17.0.184', 'note': '', 'last-seen': '2021-02-06 22:16:56'}
- !find beid 3cd2b01a123aaada2312aaa124cbawdaw
- !find ip 21.17.0.184


The command !find_linked on the other hand returns the accounts by cross referencing the database (e.g to find multi account users)
Returns:
BEIDs and account names (linked to the given BEID over by any IP/BEID that was used by the given user once).

**Comment by FliesWithWind** [comment]
Thanks for the fast answer.

It seems !find is not working for me atm. Is it on master or dev branch?

**Comment by Yoshi-E** [comment]
It should be on both branches.
Make sure you have the permission for the command enabled on the bots config page:
http://localhost:8000/

**Comment by FliesWithWind** [comment]
Thanks for the help.
It was a permission issue.
My bad.

Can't wait for the closes match support. :)

**Comment by Yoshi-E** [comment]
Added Wild card support for search queries:

e.g. !find name Yos%
will return all names that start with 'Yos'
