### ISSUE TITLE
Mission error reporting

### ISSUE THREAD

**Issue by Yoshi-E** [Yoshi-E/ArmaRconDiscordBot#31]
https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/0528d759e1d14082c70ebd7cc0d9950868bbadcd/modules/arma/module.py#L59

https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/0528d759e1d14082c70ebd7cc0d9950868bbadcd/modules/arma/readLog.py#L92

Report script errors in the mission.

**Comment by FliesWithWind** [comment]
`"FAR_isDragging>
17:02:01   Error Undefined variable in expression: grlib_player_spawned
17:02:01 File mpmissions\__CUR_MP.Altis\addons\FAR\FAR_init.sqf..., line 67
17:02:02 Deinitialized shape [Class: "B_GEN_Commander_F"; Shape: "a3\characters_f_exp\gendarmerie\b_gen_commander_f.p3d";]
17:02:02 Error in expression <p 1;!isNull player};
waitUntil {sleep 1;GRLIB_player_spawned};


"FAR_isDragging>
17:02:02   Error position: <GRLIB_player_spawned};


"FAR_isDragging>
17:02:02   Error Undefined variable in expression: grlib_player_spawned
17:02:02 File mpmissions\__CUR_MP.Altis\addons\FAR\FAR_init.sqf..., line 67
17:02:03 Error in expression <p 1;!isNull player};
waitUntil {sleep 1;GRLIB_player_spawned};

`

**Comment by Yoshi-E** [comment]
Added experimental error reporting:
42d83088b6a73a9f98a552edaf5fe7d7dd60b865

**Comment by Yoshi-E** [comment]
Errors will now be reported with:
```
:warning: Error in expression <42;  line 781408 arma_1616704832.log
Additional Errors will be suppressed for 10min.
```

To get more details use:
!view <logfile> <line number>

**Comment by Yoshi-E** [comment]
Current implementation working as indented
