### ISSUE TITLE
Log tracking issue after server restart

### ISSUE THREAD

**Issue by FliesWithWind** [Yoshi-E/ArmaRconDiscordBot#49]
When server is restarted and new log file is created, it's not being tracked.

Workaround is to restart the bot.

Also some errors appear.

> Traceback (most recent call last):
  File "/home/game2/.local/lib/python3.6/site-packages/bec_rcon.py", line 525, in listenForData
    traceback.logging.debug_exc()
AttributeError: module 'traceback' has no attribute 'logging'
Task exception was never retrieved
future: <Task finished coro=<ARC.listenForData() done, defined at /home/game2/.local/lib/python3.6/site-packages/bec_rcon.py:496> exception=AttributeError("module 'traceback' has no attribute 'logging'",)>
Traceback (most recent call last):
  File "/home/game2/.local/lib/python3.6/site-packages/bec_rcon.py", line 500, in listenForData
    answer = self.socket.recv(102400).decode(self.codec)
ConnectionRefusedError: [Errno 111] Connection refused

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/game2/.local/lib/python3.6/site-packages/bec_rcon.py", line 525, in listenForData
    traceback.logging.debug_exc()
AttributeError: module 'traceback' has no attribute 'logging'
Traceback (most recent call last):
  File "/home/game2/.local/lib/python3.6/site-packages/bec_rcon.py", line 500, in listenForData
    answer = self.socket.recv(102400).decode(self.codec)
ConnectionRefusedError: [Errno 111] Connection refused
Reconnecting to BEC Rcon

**Comment by Yoshi-E** [comment]
I fixed the error in the bec_rcon module. You should be able to update it with:
`pip install --upgrade git+https://github.com/Yoshi-E/Python-BEC-RCon.git -force-reinstall`

This however shouldn't be related to the log reading issue.
With these bot command you can read function values while the bot is running:

```
!eval print(bot.cogs['CommandArma'].readLog.current_log)
!eval print(bot.cogs['CommandArma'].readLog.getLogs())
!eval print(bot.cogs['CommandArma'].readLog.currentLinePos)
```
Does it return the current log? Is the currentLinePos > 0?

**Comment by FliesWithWind** [comment]
Sorry it's been a while, had some sever issues on the way and stopped using the bot for a while.

Here's the output of the commands.

After the restart the new log file is named same as old one, therefor it keeps reading it. However the line position is wrong.
Maybe an optional log rescan / reset after bot reconnection could solve it (if it won't affect other bot processes)? 

```
exec 'print(bot.cogs['CommandArma'].readLog.getLogs())'
['arma3server-console-2021-11-26-04:30:01.log', 'arma3server-console-2021-11-27-04:30:01.log', 'arma3server-console-2021-11-27-17:35:01.log', 'arma3server-console-2021-11-28-04:30:01.log', 'arma3server-console-2021-11-28-13:55:01.log', 'arma3server-console-2021-11-28-18:20:01.log', 'arma3server-console-2021-11-28-21:45:01.log', 'arma3server-console-2021-11-29-04:30:02.log', 'arma3server-console-2021-11-30-04:30:01.log', 'arma3server-console-2021-12-01-04:30:01.log', 'arma3server-console-2021-12-01-21:05:01.log', 'arma3server-console-2021-12-02-04:30:01.log', 'arma3server-console-2021-12-03-04:30:01.log', 'arma3server-console.log']
exec 'print(bot.cogs['CommandArma'].readLog.current_log)'
arma3server-console.log
exec 'print(bot.cogs['CommandArma'].readLog.currentLinePos)'
188681
```

```
wc -l log/console/arma3server-console.log
6190 log/console/arma3server-console.log
```

**Comment by Yoshi-E** [comment]
Doing it after bot reconnection is not recommended, as it could get stuck in an infinite loop, causing massive IOPS on the hardrive.

This bug fix triggers a reset of the log file cursor if the file size reduces, e.g. after the creation of a new empty log file.

**Comment by Yoshi-E** [comment]
Are you sure you implemented my patch db0d1115427866f5f0899a9cc13567e061ef0767 and waited long enough? The files are only checked once every 60s.

The function "watch_log" works in the following way:
1. A log file is opened as a datastream. [CODE](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L332)
2. The file will be read until the EOF is reached. Each line (string data) will be processed with "processLogLine". [CODE](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L371)
3. Now the currentLinePos is e.g. 1000, the end of the file.
4. As the server restarts, the file is emptied, as a "new" log is created.
5. The file cursor now tries to read line 1001, which does not exists, as the file is now much shorter. [CODE](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L340-L345)
6. If after 60s line 1001 still does not exists, it will check if a new log file was created [CODE](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L348)
7. If no new log file was created, it now compares the "currentLinePos" to the actual file length of the active log file. Is the currentLinePos outside the actual lenght of the active log file, it will be read from the beginning. [CODE](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L359-L364)


If that did not work, maybe test and see if this [code block](https://github.com/Yoshi-E/ArmaRconDiscordBot/blob/db0d1115427866f5f0899a9cc13567e061ef0767/modules/arma/readLog.py#L348-L367) is properly called after 60s, and where is perhaps fails.

**Comment by Yoshi-E** [comment]
I think I found the cause, will push a fix later today

**Comment by FliesWithWind** [comment]
Great! I've added some debugging logs today, but will have results with possible cause tomorrow.

**Comment by Yoshi-E** [comment]
The issue stems from a unique Linux behavior when dealing with files:
On Linux/Unix systems, once a process has a handle on a file, it can read it, even if the file is deleted.

Meaning the bot is reading the deleted "arma3server-console.log" when a new "arma3server-console.log" already exists.

At least for the log reader, the files are now identified by the disk inode number, rather than just file name.

**Comment by FliesWithWind** [comment]
I've tested it and it seems to be solved.

Thanks!
